language: node_js
node_js:
  - 12.7.0
cache: npm
install:
  - yarn install
script:
  - yarn build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  local_dir: dist
  target-branch: gh-pages
  on:
    branch: master